### PR TITLE
My second Pull Request

### PR DESCRIPTION
**Pull request by tawakuliKH**

### CODE REVIEW

**Review by NduatiKagiri — COMMENTED** [review]
Hi @tawakuliKH 👋 ,

# INVALID REVIEW REQUEST ❌ ❌  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, where you are requesting to merge changes from the main branch to a feature branch. Please note that you should push all your commits to the feature branch, and then request to merge from the feature branch to the main branch.

Your Pull Request also lacks a description. Please provide a brief summary of what you did in the project.
tawa1


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by tawakuliKH** [comment]
Hello
U already merged the two branch,
Now how can I make a new pull request?

**Comment by tawakuliKH** [comment]
Hello,
I already merged two branches of RP, how can I make new pull request?
The commits in my feature branch not coming when I make a new pull request.

**Comment by NduatiKagiri** [comment]
Hello @tawakuliKH ,
Since you will have to open a new PR in this case, if you already merged the changes, you can consider creating a new repo. This will help you relieve confusion and help you understand GitHub better, unlike trying to solve this issue which might make you get more confused. After creating the new repo, remember to follow the guidelines. Create the main branch, then a feature branch from the main branch. Remember that you should never push any changes to the main branch. While working on the feature branch, set up Linters, then copy your project files and your README file to the new project, push to the feature branch, and then create a Pull Request requesting to merge the feature branch into the main branch. And since it is against Microverse guidelines to create a new PR for a second review, kindly remember to explain to the reviewer what happened, and add this PR link to the Review Request. You can do this in your new PR, or more preferably in the 'Additional Information' space in the Review Request page.

**Pull request closed without merging**
